Repository AY1920S1-CS2103T-T13-1/main, pull requests merged in 2019-10, with the labels that each got.

#139 Status field
  src/main/java/organice/logic/parser/AddCommandParser.java
  src/main/java/organice/model/person/Donor.java
  src/main/java/organice/model/person/MatchedDonor.java
  src/main/java/organice/model/person/MatchedPatient.java
  src/main/java/organice/model/person/Patient.java
  src/main/java/organice/model/person/Status.java
  src/main/java/organice/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/organice/logic/commands/CommandTestUtil.java
  src/test/java/organice/logic/parser/AddCommandParserTest.java
  src/test/java/organice/model/person/DonorTest.java
  src/test/java/organice/model/person/MatchedDonorTest.java
  src/test/java/organice/model/person/MatchedPatientTest.java
  src/test/java/organice/model/person/PatientTest.java
  src/test/java/organice/model/person/StatusTest.java
  src/test/java/organice/storage/JsonAdaptedPersonTest.java
  src/test/java/organice/testutil/DonorBuilder.java
  src/test/java/organice/testutil/PatientBuilder.java
  src/test/java/organice/testutil/TypicalPersons.java
Labels: priority.High, type.Refactor

#149 Remove redundant persons from TypicalPerson
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/organice/logic/commands/CommandResultIntegrationTest.java
  src/test/java/organice/logic/commands/CommandTestUtil.java
  src/test/java/organice/logic/commands/MatchCommandIntegrationTest.java
  src/test/java/organice/model/ModelManagerTest.java
  src/test/java/organice/model/person/PersonTest.java
  src/test/java/organice/storage/JsonAdaptedPersonTest.java
  src/test/java/organice/storage/JsonAddressBookStorageTest.java
  src/test/java/organice/testutil/TypicalPersons.java
Labels: type.Refactor, type.Task

#150 Improve wording of Developer and User Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation

#157 Change dummy data to be populated
  src/main/java/organice/model/util/SampleDataUtil.java
Labels: severity.Low, type.Enhancement, type.Task

#152 Modify existing AB3 diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#141 Enhancements to match feature
  src/main/java/organice/logic/commands/MatchCommand.java
  src/main/java/organice/model/Model.java
  src/main/java/organice/model/ModelManager.java
  src/main/java/organice/model/person/Donor.java
  src/main/java/organice/ui/MatchCard.java
  src/main/resources/view/MatchCard.fxml
  src/main/resources/view/NumberOfMatches.fxml
  src/test/java/organice/logic/commands/AddCommandTest.java
  src/test/java/organice/logic/commands/MatchCommandIntegrationTest.java
  src/test/java/organice/logic/commands/MatchCommandTest.java
  src/test/java/organice/model/ModelStub.java
Labels: type.Enhancement

#143 Implement basic find by prefix feature
  src/main/java/organice/commons/util/StringUtil.java
  src/main/java/organice/logic/commands/FindCommand.java
  src/main/java/organice/logic/parser/ArgumentMultimap.java
  src/main/java/organice/logic/parser/FindCommandParser.java
  src/main/java/organice/model/person/NameContainsKeywordsPredicate.java
  src/main/java/organice/model/person/PersonContainsPrefixesPredicate.java
  src/test/java/organice/commons/util/StringUtilTest.java
  src/test/java/organice/logic/commands/CommandTestUtil.java
  src/test/java/organice/logic/commands/FindCommandTest.java
  src/test/java/organice/logic/parser/AddressBookParserTest.java
  src/test/java/organice/logic/parser/FindCommandParserTest.java
  src/test/java/organice/model/ModelManagerTest.java
  src/test/java/organice/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/organice/model/person/PersonContainsPrefixesPredicateTest.java
Labels: priority.High, type.Story

#158 Update User Guide for Find by Prefix Feature
  docs/UserGuide.adoc
  docs/images/findByPrefix.png
Labels: priority.High

#155 Done-command
  src/main/java/organice/logic/commands/DoneCommand.java
  src/main/java/organice/logic/parser/AddressBookParser.java
  src/main/java/organice/logic/parser/DoneCommandParser.java
  src/main/java/organice/model/ModelManager.java
  src/main/java/organice/model/person/UniquePersonList.java
  src/main/java/organice/ui/FormUiManager.java
  src/test/java/organice/logic/parser/DoneCommandParserTest.java
Labels: priority.High, type.Task
